### ISSUE TITLE
EOF Reading rows in TLS mode

### ISSUE THREAD

**Issue by vinceprignano** [jackc/pgx#103] opened 2015-10-25 22:57 UTC
I noticed that pgx driver, when using TLS and reading a lot of rows would randomly go EOF.
I am using PGX against Redshift, but I noticed a similar problem with Postgres too.

**Comment by jackc** [comment] 2015-10-26 17:11
I was able to duplicate this issue locally. Go does not support SSL renegotiation and some PostgreSQL servers are configured to do it by default. So after N bytes the connection dies. Fix by indicating to PostgreSQL during connection not to do renegotiation.

**Comment by vinceprignano** [comment] 2015-10-26 17:57
May I ask how can you set that?

**Comment by vinceprignano** [comment] 2015-10-26 18:03
Redshift doesn't support `ssl_renegotiation_limit` apparentely so I wonder if that's another issue :/

**Comment by jackc** [comment] 2015-10-26 22:38
When the client connects it can set the `ssl_renegotiation_limit`. Connection parameters can be set as part of the initial connection process. As of pgx 2.7.1 (released this morning), pgx defaults to setting this parameter to 0 (disabled) when connected over TLS. Have you tried the new release?

**Comment by vinceprignano** [comment] 2015-10-26 22:53
Just tried, it fails on Redshift
`FATA[0002] FATAL: unrecognized configuration parameter "ssl_renegotiation_limit" (SQLSTATE 42704)`

**Comment by jackc** [comment] 2015-10-26 23:10
Just did a little research on Redshift. It is based on PostgreSQL 8.0 which was initially released in 2005 and ended support in 2010. Wow... that's really old. I'm not sure why it doesn't let us disable `ssl_renegotiation_limit` as supposedly it was supported back in 8.0.

If you want to see for sure if renegotiation is the problem try connecting and running a loop of generate_series queries. If it is renegotiation it should fail at the same point every time (see https://github.com/jackc/pgx/blob/master/stress_test.go#L87 for example of how I am doing that test).

If this is the case, I'm not sure what can be done in pure Go. Redshift seems to require renegotiation and Go's TLS package doesn't support it. Not ideal, but maybe you could connect through [stunnel](https://www.stunnel.org/index.html).

**Comment by vinceprignano** [comment] 2015-10-26 23:13
Yeah bummer, is there a way to disable the default flag to be set in the if case in `2.7.1` or shall I just downgrade?

**Comment by jackc** [comment] 2015-10-27 00:11
You'll need to downgrade for the moment. Not sure what the best long-term solution is now.

**Comment by jackc** [comment] 2015-10-30 19:59
I created a Redshift database and did some testing against it with pgx with `ssl_renegotiation_limit` removed.

I was able to reproduce your original issue of loss of connection and determine it is due to SSL renegotiation (I was pretty sure this was it before -- but I wanted to be sure). So I can say with more certainty that Redshift, Go, and SSL can't play nice.

I suppose I could put in some sort of special case or override for Redshift with SSL, but I'm loath to enable something that is guaranteed to cause seemingly random connection loss. I prefer getting an immediate error on connection rather than mysterious failure later.

**Comment by vinceprignano** [comment] 2015-11-04 18:17
I agree with failing fast and have clear understanding what's going on.

**Comment by vinceprignano** [comment] 2016-01-22 17:48
hey @jackc, regarding this issue, I am still seeing random EOFs sometimes, the only thing that I would like to do is to release and close the connection from the pool when that happens so that the application client can implement a retry based on that.

At the moment, when a connection goes EOF in the pool, it never gets released and usually just gets stuck, do you have any hint for this?

**Comment by jackc** [comment] 2016-01-23 17:18
A few questions:

Is this using TLS?
Is this still against Redshift?
What version of pgx?

**Comment by vinceprignano** [comment] 2016-01-23 17:20
Still TLS, with Redshift and last version of pgz that I forked to remove
the disable renegotiation flag.

**Comment by jackc** [comment] 2016-01-27 00:43
I've tried without success to duplicate this. 

Wasn't able to get it to fail with PostgreSQL on OSX as apparently my version of openssl disables renegotiation altogether. So I couldn't introduce a true failure.

I hacked my test code to introduce a EOF in my SSL stress test the pool seemed to handle it.

So I'm not sure what might be going on. If you have any way of reproducing this outside of Redshift, I might be able to find a resolution.

That said, for your particular case, I would suggest perhaps it would be possible to prevent the error altogether, rather than recover from it when it does. I believe the redshift renegotiation limit is 512MB. So presumably you can do a fair number of queries before a connection dies. It might be possible in your fork to keep track of the number of queries executed, and automatically kill the connection on release to pool when 100 or 1000 queries have been executed.

**Comment by vinceprignano** [comment] 2016-01-27 02:27
Hey @jackc, I can provide a Redshift instance for testing purposes if you want. Or I can run the tests against ours.

**Comment by jackc** [comment] 2016-01-29 23:40
I was able to test against a Linux PostgreSQL install that used SSL renegotiation. I wasn't able to get the pool to totally lock up, but I was able to get in a place where a bad connection was put back in the pool and wasn't detected until the next time it was used. Tracking this down led me to an bug in rxMsg. It's fixed on master. I suspect this may resolve your issue.

**Comment by vinceprignano** [comment] 2016-01-31 00:29
Thanks! I am gonna update and let you know if it happens again :)

**Comment by jackc** [comment] 2016-03-07 15:03
Without any further bug reports, I am going to consider this closed. Feel free to reopen if the problem reoccurs.

**Comment by vinceprignano** [comment] 2016-08-09 04:00
@jackc it seems that renegotiation is supported in 1.7, worth testing it? https://github.com/golang/go/issues/5742

**Comment by jackc** [comment] 2016-08-10 22:02
If the new Go TLS code is compatible with Redshift it should be trivial to enable it.

I don't have Go 1.7 or a redshift box handy, but I coded what should be the fix and pushed it to branch [go17-redshift-test] (https://github.com/jackc/pgx/tree/go17-redshift-test). The only change is not to send the disable ssl renegotiation message to PostgreSQL if the client supplies pgx with a `tls.Config` that has `Renegotiation` enabled.

If you can, try it out and let me know if it works.

**Comment by jackc** [comment] 2016-10-01 12:51
Just tested current master against a new Redshift cluster. It looks like `ssl_renegotiation_limit` is now supported by Redshift. So TLS connections work fine out of the box.

**Closed by jackc** 2016-10-01 12:51 UTC
