### ISSUE TITLE
Scanning into custom type pointer doesn't work

### ISSUE THREAD

**Issue by anpryl** [jackc/pgx#1326] opened 2022-10-04 08:57 UTC
**Describe the bug**

After migration from v4 to v5 scanning into fields with custom types and pointers doesn't work anymore. Looks like degradation.

Also I found unused function `scanUnknownType`. It looks it might help.

**To Reproduce**

Here are test cases for custom types: https://github.com/jackc/pgx/commit/06e9f9692bd333279e2880f466202ffee05937d7
Only `TestRowScannerCustomTypePointers` fails.

**Expected behavior**
Scanning should work for pointers on custom types.

**Actual behavior**
It leads to error: `&errors.errorString{s:"cannot scan varchar (OID 1043) in text format into **my.CustomType"},

**Version**
 - Go: go1.19 linux/amd64
 - PostgreSQL: PostgreSQL 13.8 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 11.3.0, 64-bit
 - pgx: v5.0.1

**Comment by jackc** [comment] 2022-10-08 14:11
There's actually two issues contained in your test. One is scanning to a pointer to a pointer to a renamed type.

```go
func TestMapScanPointerToRenamedType(t *testing.T) {
	srcBuf := []byte("foo")
	m := pgtype.NewMap()

	var rs *_string
	err := m.Scan(pgtype.TextOID, pgx.TextFormatCode, srcBuf, &rs)
	assert.NoError(t, err)
	require.NotNil(t, rs)
	assert.Equal(t, "foo", string(*rs))
}
```

This is now fixed.

---

The other is scanning a `null` of the wrong type into a pointer to a pointer. e.g.

```go
var n *int32
err = conn.QueryRow(ctx, "select null::text").Scan(&n)
```

This works on `v4` and does not work on `v5`. Though I'm not entirely that this *should* work. It means an incorrect query / scan type combination will happen to work if the result is `null` but will fail later with the same query if a non `null` is returned.

The problem is `select null` implicitly decides that the type of the column is `text`. So scanning that into `**int32` will fail.

The reason `v5` fails is it starts with the PostgreSQL type to determine how to scan the value. `v4` starts with the Go type. And the types *are* incompatible -- it just so happens that the `null` value is the same for all types which is why incompatible types worked in `v4`.

---

Yuck... well, I got it working, though with a really nasty hack.

First, I was able to reduce the test to:

```go
func TestMapScanNullToWrongType(t *testing.T) {
	m := pgtype.NewMap()

	var n *int32
	err := m.Scan(pgtype.TextOID, pgx.TextFormatCode, nil, &n)
	assert.NoError(t, err)
	assert.Nil(t, n)

	var pn pgtype.Int4
	err = m.Scan(pgtype.TextOID, pgx.TextFormatCode, nil, &pn)
	assert.NoError(t, err)
	assert.False(t, pn.Valid)
}
```

The "fix" is to check for `null` on the failure path and then try *all* registered types to find one that can handle it.

```go
func (plan *scanPlanFail) Scan(src []byte, dst any) error {
	// If src is NULL it might be possible to scan into dst even though it is the types are not compatible. While this
	// may seem to be a contrived case it can occur when selecting NULL directly. PostgreSQL assigns it the type of text.
	// It would be surprising to the caller to have to cast the NULL (e.g. `select null::int`). So try to figure out a
	// compatible data type for dst and scan with that.
	//
	// See https://github.com/jackc/pgx/issues/1326
	if src == nil {
		// As a horrible hack try all types to find anything that can scan into dst.
		for oid := range plan.m.oidToType {
			// using planScan instead of Scan or PlanScan to avoid polluting the planned scan cache.
			plan := plan.m.planScan(oid, plan.formatCode, dst)
			if _, ok := plan.(*scanPlanFail); !ok {
				return plan.Scan(src, dst)
			}
		}
	}
```

**Closed by jackc** 2022-10-08 14:11 UTC
Labels: bug
