### ISSUE TITLE
Bug with 5.4.0 version and TypeMap

### ISSUE THREAD

**Issue by Alexfilus** [jackc/pgx#1650] opened 2023-06-18 09:22 UTC
**Describe the bug**
When simple protocol is on and concurrent queries with arguments are performing I got a panic 
fatal error: concurrent map read and map write
goroutine 583 [running]:
github.com/jackc/pgx/v5/pgtype.(*Map).TypeForValue(0xc00078e1c0?, {0x16b3140, 0x1cc2db8})
	/Users/aleksandrfilippenko/go/src/pgx-test/vendor/github.com/jackc/pgx/v5/pgtype/pgtype.go:325 +0x225

**To Reproduce**
Just run test from this file 
https://github.com/Alexfilus/pgx-test/blob/main/tests/concurrent_test.go
running docker is required

**Expected behavior**
All tests are passed

**Actual behavior**
got a panic 
fatal error: concurrent map read and map write
goroutine 583 [running]:
github.com/jackc/pgx/v5/pgtype.(*Map).TypeForValue(0xc00078e1c0?, {0x16b3140, 0x1cc2db8})
	/Users/aleksandrfilippenko/go/src/pgx-test/vendor/github.com/jackc/pgx/v5/pgtype/pgtype.go:325 +0x225

**Version**
 - Go: `$ go version` -> go version go1.20.4 darwin/amd64
 - PostgreSQL: 15 from docker. I also tried 13. Same result.
 - pgx: `$ grep 'github.com/jackc/pgx/v[0-9]' go.mod` -> v5.4.0

**Additional context**
Reproducing only with pgx 5.4.0 and cfg.ConnConfig.DefaultQueryExecMode = pgx.QueryExecModeSimpleProtocol
By some reason typeMap is empty at the begining and filling while queries are performing. 
Not reproducing with pgx 5.3.1 or with default QueryExecMode.

**Comment by jackc** [comment] 2023-06-18 11:26
@lzakharov Can you take a look at this? It seems #1631 wasn't actually safe.

Sharing `Map.reflectTypeToType` is a problem. This path seems to only be triggered with the simple protocol. This is tricky because `Map.reflectTypeToType` is lazily built on first access. Eagerly building it would resolve this, but the problem is every type registration invalidates the map. It would have very poor performance.

**Comment by lzakharov** [comment] 2023-06-18 12:09
As I can see, this can be fixed this lazy map building https://github.com/jackc/pgx/blob/9a5ead904858db5afe2073370d33f474db3c83ad/pgtype/pgtype.go#L321-L323
into the default map initialization `initDefaultMap`. Since writing to the default map only occur during creation it looks safe. @jackc if you don't see any other issues I can prepare PR soon.

I've checked this fix in the provided repository with tests - the errors are gone.

**Comment by jackc** [comment] 2023-06-18 12:15
@lzakharov As far as I can tell that should work.

**Comment by jackc** [comment] 2023-06-18 13:29
Fixed by @lzakharov in 7c386112e35fc30d85f26923865504edb8d4758e. I tagged v5.4.1.

**Closed by jackc** 2023-06-18 13:29 UTC
Labels: bug

**Comment by drakkan** [comment] 2023-06-18 13:45
Hello, thank you for the quick fix. I did some tests in database sql mode (so query exec mode "cache statement") and the problematic code never seems to hit. 

Can you confirm that the problem only occurs with the simple protocol or can it occur for other modes of query exec as well? Thank you

**Comment by jackc** [comment] 2023-06-18 13:55
The only place I know of that hits that code path is when a query parameter needs to be encoded when pgx doesn't know what the actual PostgreSQL type is. So I think it could also occur in `QueryExecModeExec`.

**Comment by drakkan** [comment] 2023-06-18 14:00
> The only place I know of that hits that code path is when a query parameter needs to be encoded when pgx doesn't know what the actual PostgreSQL type is. So I think it could also occur in `QueryExecModeExec`.

Thank you for confirming. I have just released SFTPGo v2.5.2 with pgx 5.4.0 and I'll wait a week or so before tagging a new version with this fix since it uses database/sql and `QueryExecModeCacheStatement`

**Comment by Alexfilus** [comment] 2023-06-18 14:29
@lzakharov Thank you for quick fix!
@jackc What do you think about my concurrent test to main pgx repo? With all QueryExecMode variants?

**Comment by drakkan** [comment] 2023-06-19 17:27
I added a similar test case for stdlib in #1653. It passes for all QueryExecMode even without this patch
