### ISSUE TITLE
Canceling a Query with context.WithTimeout causes the next request to have an error

### ISSUE THREAD

**Issue by melwute** [jackc/pgx#506] opened 2019-01-27 16:42 UTC
When writing a HttpHandler that used a context.WithTimeout I noticed after a timeout occurs the next request that uses the ConnPool gives a "set tcp [::1]:59627: use of closed network connection" error. 

```
package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"time"

	"github.com/jackc/pgx"
)

type user struct {
	id       int
	email    string
	password string
}

func GetUser(c context.Context, db *pgx.ConnPool) (*user, error) {
	row := db.QueryRowEx(c, `
	SELECT id, email, password
	FROM public.user, pg_sleep(10)
	limit 1;`, nil)
	u := user{}
	err := row.Scan(&u.id, &u.email, &u.password)
	if err != nil {
		return nil, err
	}
	return &u, nil
}

func main() {
	config, err := pgx.ParseEnvLibpq()
	if err != nil {
		log.Fatal(err)
	}
	poolConfig := pgx.ConnPoolConfig{
		ConnConfig: config,
	}
	db, err := pgx.NewConnPool(poolConfig)
	if err != nil {
		log.Fatal(err)
	}

	//Calling this twice causes a "set tcp [::1]:60944: use of closed network connection" error
	//60944 seems to be a random number
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		ctx, cancel := context.WithTimeout(r.Context(), 2*time.Second)
		defer cancel()
		r = r.WithContext(ctx)

		u, err := GetUser(r.Context(), db)
		if err != nil {
			log.Println(err)
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		fmt.Fprintf(w, "That query took a while! %v,%v,%v", u.id, u.email, u.password)
	})

	http.ListenAndServe(":8080", nil)
}

```

**Comment by jackc** [comment] 2019-01-29 04:55
I was only able to duplicate this when using a TLS connection. That led me to discover that TLS connections are permanently broken once a deadline is triggered. But worse is that they permanently report the error as temporary :disappointed: (https://github.com/golang/go/issues/29971).

Anyway, it basically boils down to all Write errors are fatal all the time. I just made this change to master. Let me know if it works.

**Comment by melwute** [comment] 2019-01-30 03:02
This didn't seem to fix my issue. I'm not sure if this is related but I traced the error source for that first query that timed out and it seems like we didn't kill the connection there because the error type was of a different type than a net.Error? Looks like it was a net.OpError, but I could be misreading this as I am new to go. See the attached image for more info.

![issue-506](https://user-images.githubusercontent.com/1691372/51955314-0c3ada80-2409-11e9-9acc-a18bcba307d9.PNG)

**Comment by melwute** [comment] 2019-01-30 13:03
Changing that error handling to the following seemed to fix my problem.
```
if err != nil {
	switch err := err.(type) {
	case net.Error:
		if err.Timeout() {
			c.die(err)
		}
	case *net.OpError:
		if err.Timeout() {
			c.die(err)
		}
	}
	return nil, err
}
```

**Comment by jackc** [comment] 2019-01-30 15:19
I don't think the difference is between `net.Error` and `*net.OpError`. `net.Error` is an interface that `*net.OpError` implements. The effective difference in the code is that the original code kills the connection on any error except a `Timeout` `net.Error`. The new code code inverts that logic -- it only kills `Timeout` `net.Error`s.

How are you connecting to the database? I was only to duplicate this issue originally with a TLS connection, but was unable to do so again after fixing the write issue.

**Comment by melwute** [comment] 2019-01-31 00:35
I'm not 100% sure, this is running locally on my windows 10 machine and I'm using whatever the default settings are when you install postgres locally. The only difference between the sample code I provided and the one I used is this is my following "super secure" config settings.

```
config := pgx.ConnPoolConfig{
	ConnConfig: pgx.ConnConfig{
		Host:     "localhost",
		User:     "app",
		Password: "password",
		Database: "postgres",
	},
}
```

**Comment by jackc** [comment] 2019-02-16 15:21
Well, if you are on Windows then you definitely are using TCP, not a Unix domain socket to connect. And if it is localhost then it presumably wouldn't be a TLS connection.

Hmmm, This might be specific to Windows.

I presume you are running the latest version of Go and pgx?

**Comment by melwute** [comment] 2019-02-17 15:16
go version go1.11.4 windows/amd64
and pgx should be the latest as well.

**Comment by jackc** [comment] 2019-03-09 17:50
I was finally able to duplicate this on a Windows machine. The direct cause is the asynchronous query cancellation gets an unexpected error and closes the connection. However, the connection has already been returned to the pool and the pool doesn't realize that the connection is now bad.

There are a few possible solutions.

The unexpected error is that Windows and/or PostgreSQL on Windows seems to handle connection closures differently than Linux. The procedure for closing a PostgreSQL connection is to send the terminate message. The PostgreSQL server will close the connection. The client reads until it sees `io.EOF`. However, in some circumstances that I haven't been able determine the cause of, the read returns a different error (`wsarecv: An existing connection was forcibly closed by the remote host.`). This also makes almost all the tests fail on Windows.

So one solution is to track down this different Windows behavior. I don't usually work on Windows though...

Another solution is to better handle the case of a connection dying while it is in the pool. This is a pretty subtle edge case. I think I'd prefer to remove the possibility entirely rather than fix that case.

And that leads to the last option which is described in #517.

**Comment by jackc** [comment] 2019-09-16 14:22
This should be resolved in the recently released `v4`. Rather than trying to recover from potentially fatal conditions after a context cancellation, `v4` treats any potentially fatal condition as fatal and closes the connection. This eliminate the problem of trying to use a dead connection.

**Closed by jackc** 2019-09-16 14:22 UTC
