### ISSUE TITLE
possible problems with large objects (connection busy )

### ISSUE THREAD

**Issue by volkmarbuehringer** [jackc/pgx#710] opened 2020-04-03 10:34 UTC
Hi,

I am using pgx 4.6 and go 1.14
I use pgxpool for the db-connections.

I use largeObjects for streaming documents out of postgres into a POST request.
If the Post request aborts I have sometimes problems with busy conn  on this transaction.

The closing of the large object and rollback of the transaction doesn't work because of this error.
I tried to discard the remaining data of the large object but this doesn't work either.

The only thing I could do is to isolate the large object access into an extra transaction, so the rest of the program can still work. So I have only errors from largeobject.Close and tx.Rollback.

Is there another way to clean the unfinished reader from the post-Request ?

Thanks.

**Comment by jackc** [comment] 2020-04-04 14:12
Do you have a way of reproducing this? It's a hard to determine whether the issue is pgx or how the application is using it from just the description.

**Comment by bfontaine** [comment] 2022-11-02 09:11
Closing this since it’s not reproducible and the issue is two-years old.

**Closed by bfontaine** 2022-11-02 09:11 UTC
