### ISSUE TITLE
Connection in broken transaction returned after commit fails

### ISSUE THREAD

**Issue by horgh** [jackc/pgx#787] opened 2020-07-10 19:27 UTC
Hello!

A program I use has a transaction with a local `statement_timeout` set. Occasionally the `COMMIT` fails due to hitting the timeout.

Prior to #780 (I believe), it seemed that the connection was never re-used in this case. I found that after this change, queries in other parts of my program occasionally throw this error:

```
ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02)
```

I've worked around this by always sending a rollback for the transaction (previously there was no rollback if the commit failed). However, I wonder if it is intended that a connection in this state is available for later use? I'm not sure if there'd be a good way to avoid it, so maybe it is up to the caller to deal with, but I thought I'd ask just in case.

I am using Go 1.14.4 and pgx v4.7.1 by the way.

Thank you!

**Comment by jackc** [comment] 2020-07-10 23:37
Do have an example that can produce this error?

I would have expected https://github.com/jackc/pgx/blob/11428bbc02a720cf612d528ae07ab7aa8422ba18/pgxpool/conn.go#L30-L33 to handle this case. When the returned connection is not in an idle state it should be terminated.

**Comment by horgh** [comment] 2020-07-13 15:10
Here is a program that demonstrates it: https://gist.github.com/horgh/34f2c2b774ead1a3ac5ebefe71760faf

An example run for me shows this:

```
2020/07/13 15:08:26 error scanning row: ERROR: canceling statement due to statement timeout (SQLSTATE 57014)
2020/07/13 15:08:28 error scanning row: ERROR: canceling statement due to statement timeout (SQLSTATE 57014)
2020/07/13 15:08:28 error scanning row: ERROR: canceling statement due to statement timeout (SQLSTATE 57014)
2020/07/13 15:08:31 error committing: ERROR: canceling statement due to statement timeout (SQLSTATE 57014)
2020/07/13 15:08:31 error starting transaction: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02)
(process exited)
```

I found that if there is a `Commit()` call at all, the `BeginTx()` will fail with that last error. My workaround for my real program was to remove the `Commit()` and always `Rollback()` in a `defer`. This is fine for my use case as it is a read only transaction.

**Comment by jackc** [comment] 2020-07-14 03:51
Ah, this is using the `database/sql` connection pool.

I've tried your example (modified slightly since I don't have the every_account table) and I was actually writing a response that said I couldn't get it to fail when it finally did once. Now in maybe 10-15 minutes of running it I've only managed to get two failures. I even changed the select to include a pg_sleep so it would always timeout but no difference.

I don't see where this could be failing in pgx though -- the transaction code in stdlib is a very minimal wrapper around the native pgx tx code.

https://github.com/jackc/pgx/blob/5b498c4529207b8dd741ebea6136a37794a6b182/stdlib/sql.go#L318-L323

and

https://github.com/jackc/pgx/blob/5b498c4529207b8dd741ebea6136a37794a6b182/stdlib/sql.go#L714-L721

I know that in general [it's always my fault](https://blog.codinghorror.com/the-first-rule-of-programming-its-always-your-fault/), but this really smells like a problem with `database/sql` (some sort of race condition if I had to guess -- given the fact that it doesn't always fail when a statement timeout is triggered in the transaction).

...

Oh, wait. I just read your error log again. This is a really pathological case. The actual statement_timeout is occurring **while** executing `commit`. So the client thinks it executed `commit` so the transaction has either been committed or rolled back but in fact it is as if the `commit` was never sent.

Okay, I just pushed 9b480f4 to master. Now if a commit fails it will check to see if the connection state is still in a transaction and if it is then it terminates the connection. I _think_ this should solve your issue, but given that I can't reliably reproduce it I can't be sure.

**Comment by horgh** [comment] 2020-07-14 15:41
Sweet! I tested your change and the program continues now if the `commit` hits that case:

```
$ ./test-commit-rollback-err [snip]
2020/07/14 15:38:09 error committing: commit unexpectedly resulted in rollback
2020/07/14 15:38:10 error scanning row: ERROR: canceling statement due to statement timeout (SQLSTATE 57014)
2020/07/14 15:38:17 error scanning row: ERROR: canceling statement due to statement timeout (SQLSTATE 57014)
2020/07/14 15:38:18 error scanning row: ERROR: canceling statement due to statement timeout (SQLSTATE 57014)
2020/07/14 15:38:19 error scanning row: ERROR: canceling statement due to statement timeout (SQLSTATE 57014)
2020/07/14 15:38:22 error scanning row: ERROR: canceling statement due to statement timeout (SQLSTATE 57014)
2020/07/14 15:38:23 error scanning row: ERROR: canceling statement due to statement timeout (SQLSTATE 57014)
2020/07/14 15:38:27 error committing: ERROR: canceling statement due to statement timeout (SQLSTATE 57014)
2020/07/14 15:38:32 error scanning row: ERROR: canceling statement due to statement timeout (SQLSTATE 57014)
^C
```

Thank you for investigating and fixing it!

**Comment by jackc** [comment] 2020-07-14 17:10
New release v4.7.2 includes this fix.

**Closed by jackc** 2020-07-14 17:10 UTC
