### ISSUE TITLE
conn busy

### ISSUE THREAD

**Issue by lpar** [jackc/pgx#622] opened 2019-10-03 22:33 UTC
I would expect this code to acquire two connections, one for each goroutine running a test case, since each test holds the connection unreleased for a second:

```
package main

import (
	"context"
	"fmt"
	"os"
	"testing"
	"time"

	"github.com/jackc/pgx/v4"
	"github.com/jackc/pgx/v4/pgxpool"
)

var testpool *pgxpool.Pool

func TestMain(m *testing.M) {
	pconf, err := pgxpool.ParseConfig(dburl)
	if err != nil {
		panic(err)
	}
	pconf.AfterConnect = func(ctx context.Context, conn *pgx.Conn) error {
		fmt.Println("acquired a connection from the pool")
		return nil
	}
	fmt.Println("connecting")
	testpool, err = pgxpool.ConnectConfig(context.Background(), pconf)
	if err != nil {
		panic(err)
	}
	code := m.Run()
	testpool.Close()
	os.Exit(code)
}

func Test_P1(t *testing.T) {
	conn, err := testpool.Acquire(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	res, err := conn.Query(context.Background(), "select 1;")
	if err != nil {
		t.Fatal(err)
	}
	res.Next()
	time.Sleep(time.Second)
	conn.Release()
}

func Test_P2(t *testing.T) {
	conn, err := testpool.Acquire(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	res, err := conn.Query(context.Background(), "select 2;")
	if err != nil {
		t.Fatal(err)
	}
	res.Next()
	time.Sleep(time.Second)
	conn.Release()
}
```

Instead:

```
connecting
acquired a connection from the pool
--- FAIL: Test_P2 (0.00s)
    main_test.go:56: conn busy
FAIL
```

If I do the same thing but using main() and goroutines:

```
package main

import (
	"context"
	"fmt"
	"time"

	"github.com/jackc/pgx/v4"
	"github.com/jackc/pgx/v4/pgxpool"
)

var pool *pgxpool.Pool

func main() {
	pconf, err := pgxpool.ParseConfig(dburl)
	if err != nil {
		panic(err)
	}
	pconf.AfterConnect = func(ctx context.Context, conn *pgx.Conn) error {
		fmt.Println("acquired a connection from the pool")
		return nil
	}
	fmt.Println("connecting")
	pool, err := pgxpool.ConnectConfig(context.Background(), pconf)
	if err != nil {
		panic(err)
	}
	go doConn(pool)
	go doConn(pool)
	time.Sleep(2*time.Second)
	pool.Close()
}


func doConn(pool *pgxpool.Pool) {
	conn1, err := pool.Acquire(context.Background())
	if err != nil {
		panic(err)
	}
	time.Sleep(time.Second)
	conn1.Release()
}
```

...it works as expected:

```
connecting
acquired a connection from the pool
acquired a connection from the pool
%
```

Pretty sure this isn't the same cause as #610. Maybe there's some subtlety of the test package involved? It's only connecting once though...

**Comment by jackc** [comment] 2019-10-12 16:31
First, your tests are not running in parallel. You need to use `t.Parallel()`.

Second, `res` is never closed. You need to either call `Next()` until it returns false or explicitly call `Close()`.

However, it still is a bug that releasing a busy connection is not caught by the pool. So that is now fixed. Releasing a busy connection causes the connection to be closed and removed from the pool

**Closed by jackc** 2019-10-12 16:31 UTC

**Comment by lpar** [comment] 2019-10-13 15:24
Hmm, I thought tests ran in parallel because I used to have to use `-p 1` to prevent them from running in parallel. I guess that changed at some point.

Sorry about the bug in the example. I'd actually be fine with simply getting an error on trying to close a connection with statements open, as that's really a logical error and might be better flagged. Db2, for example, will return an error if you try to close a connection with statements left open. I can imagine situations where one might try to return rows from a query from a function while allowing a connection to be defer closed, and end up with a confusing error.

**Comment by jackc** [comment] 2019-10-13 20:15
`Release()` doesn't return an error. So the only thing that could be done other than close the connection would be to panic.

**Comment by lpar** [comment] 2019-10-13 20:42
You could add an error return to `Release()` without breaking existing code though, right? Or does Postgres itself not return an error?

**Comment by jackc** [comment] 2019-10-14 15:10
It's not a PostgreSQL error at all. The connection pool is on the Go side. The problem is returning a connection to the pool when it is still busy. Prior to 93a2aa5b2f4a3bcdcf601c620276b055db87c2a4 this would cause the error you saw when the connection was next checked out of the pool. Now it closes the connection.

I suppose that adding an error to `Release()` would not be a breaking change, but it's really not a run time error. It either should automatically close the conn (the new behavior) or it should be considered a bug and panic.

**Comment by lpar** [comment] 2019-10-14 17:15
I don't think libraries should panic unless the situation is truly impossible to recover, but I don't like hiding the error either. Anyway, your call, obviously, and I'm going to see if I can find a linter that checks for missing `.Close()` invocations.
