### ISSUE TITLE
error message 'Unknown type' must have name of type

### ISSUE THREAD

**Issue by ruslanBik4** [jackc/pgx#611] opened 2019-09-23 10:47 UTC
I get this error from time to time. Every time I must review my code & procedure code & make test procedure for undastanding this message.
 may be, it is good Idea - include in messga type name?

**Comment by jackc** [comment] 2019-09-23 12:17
Can you give me an example that produces this error?

**Comment by ruslanBik4** [comment] 2019-09-23 13:59
Unknown type 'datarange', OID=3812

**Comment by ruslanBik4** [comment] 2019-09-23 14:03
May be it is very 'developer-frendly' if pgx created custom error object and place it to errRows ?

**Comment by jackc** [comment] 2019-09-26 13:58
Sorry, still not understanding the context. Can you give me an example with:

1. What code you run
2. What error is actually returned
3. What error you wish was returned

**Comment by ruslanBik4** [comment] 2019-10-04 10:54
1. Init - 	pool, err = pgxpool.ConnectConfig(context.Background(), poolCfg)
 run SQL -	rows, err := pool.Query(context.Background(), sql, args...)

 Example, sql = "select * from rpt_positions_hi_low()"
where rpt_positions_hi_low return 'positions_hi_low' (it is a table of DB)

2. err = error{"Unknown type"}
3. I wish to get error as "Unknown type 'positions_hi_low' (OID = XXXX)

 In this case, I know about "Unknown type" (procedure return one column) but others case may be very complicated to find a source of error.

 Also, why dosn't pgx unknow type of table? 1 version do it without any problem!

**Comment by jackc** [comment] 2019-10-12 15:34
So if I'm understanding correctly, the core issue would be showing the name for the unknown OID. This would be rather difficult. The OID is the only information we have at that point. It would be necessary to do another query to retrieve the name.

**Comment by ruslanBik4** [comment] 2019-10-27 13:54
I get a procedure (header):
create function rpt_accounts_hi_low(startdate date, enddate date, accounts integer[])
    returns table (account integer, date date, hi double precision, low double precision)

in call get error "unknow type"
What type it minds? All types of in/out params are standart!
 If pgx will return even OIDs, i can fixed it.
 I dont know what to do!

**Comment by jackc** [comment] 2019-10-28 13:53
Can you provide example code that exhibits this behavior?

**Comment by bfontaine** [comment] 2022-11-04 10:01
I’m closing this issue since it as been waiting for a reproducible example for more than three years.

**Closed by bfontaine** 2022-11-04 10:01 UTC
