### ISSUE TITLE
Unable to connect to remote database using hostname

### ISSUE THREAD

**Issue by xeals** [jackc/pgx#453] opened 2018-08-29 09:48 UTC
Disclosure: I'm using the `stdlib` driver instead of `pgx` on its own.

Attempting to connect using a remote hostname instead of IP address fails.

```go
sql.Connect("pgx", "host=db user=username password=password dbname=dbname")
// or
sql.Connect("pgx", "postgres://username:password@db/dbname")
```

both fail with the error `panic: dial unix db/.s.PGSQL.5432: connect: no such file or directory`.

I've seen a suggestion for other databases to use parentheses around the hostname, but this also fails:

```go
sql.Connect("pgx", "postgres://username:password@(db)/dbname")
```

```
panic: dial tcp: lookup (db): no such host
```

Accessing the remote via hostname works in other programs, e.g., `ping`, and I'm able to connect when specifying the IP address.

Using `pgx` 3.2.0, Go 1.10, Postgres 10.

**Comment by jackc** [comment] 2018-09-02 02:44
What is this `sql.Connect`? I'm only aware of `sql.Open` and `sql.OpenDB`. And I'm not able to duplicate the issue with them.

**Comment by bfontaine** [comment] 2022-10-28 14:43
I’m closing this since the issue is 4 years old and not reproducible.

**Closed by bfontaine** 2022-10-28 14:43 UTC
