### ISSUE TITLE
Data race when scanning from closed poolRows

### ISSUE THREAD

**Issue by georgysavva** [jackc/pgx#785] opened 2020-07-02 09:06 UTC
I discovered a data race warning when I was running tests of my library that uses pgx. One of the tests does this:  
1. Queries rows from pgx pool.
2. Closes them.
3. And after that scans one more time. 

Pgx doesn't return an error and even fills the destinations with valid data, so I thought it's a valid case.
But it causes data race actually. 

As I understand, this happens because `poolRows.Close()` releases the underlying connection:
https://github.com/jackc/pgx/blob/eeda0368e66fafed0a3db500108bdb87b657a88a/pgxpool/rows.go#L34-L40

And another goroutine starts using it, but then `poolRows.Scan()` accesses it again.

I understand that scanning from closed rows is a highly unusual situation, but I think pgxpool should be explicit about it either return an error or document the behaviour.  Because from my guess It looked as it's allowed. 

BTW here is the DATA RACE stack trace:
```
==================
WARNING: DATA RACE
Write at 0x00c0000e60a8 by goroutine 38:
  github.com/jackc/pgconn.(*PgConn).execExtendedPrefix()
      /home/travis/gopath/pkg/mod/github.com/jackc/pgconn@v1.5.1-0.20200601181101-fa742c524853/pgconn.go:949 +0xb3
  github.com/jackc/pgconn.(*PgConn).ExecPrepared()
      /home/travis/gopath/pkg/mod/github.com/jackc/pgconn@v1.5.1-0.20200601181101-fa742c524853/pgconn.go:935 +0x91
  github.com/jackc/pgx/v4.(*Conn).Query()
      /home/travis/gopath/pkg/mod/github.com/jackc/pgx/v4@v4.6.1-0.20200606145419-4e5062306904/conn.go:704 +0x153b
  github.com/jackc/pgx/v4/pgxpool.(*Conn).Query()
      /home/travis/gopath/pkg/mod/github.com/jackc/pgx/v4@v4.6.1-0.20200606145419-4e5062306904/pgxpool/conn.go:54 +0x136
  github.com/jackc/pgx/v4/pgxpool.(*Pool).Query()
      /home/travis/gopath/pkg/mod/github.com/jackc/pgx/v4@v4.6.1-0.20200606145419-4e5062306904/pgxpool/pool.go:409 +0xf1
  github.com/georgysavva/scany/pgxscan_test.TestRowScanner_Scan()
      /home/travis/gopath/src/github.com/georgysavva/scany/pgxscan/pgxscan_test.go:149 +0xd1
  testing.tRunner()
      /home/travis/.gimme/versions/go1.13.12.linux.amd64/src/testing/testing.go:909 +0x199
Previous read at 0x00c0000e60a8 by goroutine 40:
  github.com/jackc/pgx/v4.(*connRows).FieldDescriptions()
      /home/travis/gopath/pkg/mod/github.com/jackc/pgconn@v1.5.1-0.20200601181101-fa742c524853/pgconn.go:1358 +0x65
  github.com/jackc/pgx/v4/pgxpool.(*poolRows).FieldDescriptions()
      /home/travis/gopath/pkg/mod/github.com/jackc/pgx/v4@v4.6.1-0.20200606145419-4e5062306904/pgxpool/rows.go:54 +0x54
  github.com/georgysavva/scany/pgxscan.RowsAdapter.Columns()
      /home/travis/gopath/src/github.com/georgysavva/scany/pgxscan/pgxscan.go:107 +0x71
  github.com/georgysavva/scany/pgxscan.(*RowsAdapter).Columns()
      <autogenerated>:1 +0x71
  github.com/georgysavva/scany/dbscan.startScanner()
      /home/travis/gopath/src/github.com/georgysavva/scany/dbscan/dbscan.go:258 +0x6e
  github.com/georgysavva/scany/dbscan.(*RowScanner).doScan()
      /home/travis/gopath/src/github.com/georgysavva/scany/dbscan/dbscan.go:240 +0x274
  github.com/georgysavva/scany/dbscan.(*RowScanner).Scan()
      /home/travis/gopath/src/github.com/georgysavva/scany/dbscan/dbscan.go:208 +0x180
  github.com/georgysavva/scany/pgxscan.(*RowScanner).Scan()
      /home/travis/gopath/src/github.com/georgysavva/scany/pgxscan/pgxscan.go:83 +0x7b
  github.com/georgysavva/scany/pgxscan_test.TestRowScanner_Scan_closedRows()
      /home/travis/gopath/src/github.com/georgysavva/scany/pgxscan/pgxscan_test.go:200 +0x247
  testing.tRunner()
      /home/travis/.gimme/versions/go1.13.12.linux.amd64/src/testing/testing.go:909 +0x199
Goroutine 38 (running) created at:
  testing.(*T).Run()
      /home/travis/.gimme/versions/go1.13.12.linux.amd64/src/testing/testing.go:960 +0x651
  testing.runTests.func1()
      /home/travis/.gimme/versions/go1.13.12.linux.amd64/src/testing/testing.go:1202 +0xa6
  testing.tRunner()
      /home/travis/.gimme/versions/go1.13.12.linux.amd64/src/testing/testing.go:909 +0x199
  testing.runTests()
      /home/travis/.gimme/versions/go1.13.12.linux.amd64/src/testing/testing.go:1200 +0x521
  testing.(*M).Run()
      /home/travis/.gimme/versions/go1.13.12.linux.amd64/src/testing/testing.go:1117 +0x2ff
  github.com/georgysavva/scany/pgxscan_test.TestMain.func1()
      /home/travis/gopath/src/github.com/georgysavva/scany/pgxscan/pgxscan_test.go:218 +0x2b1
  github.com/georgysavva/scany/pgxscan_test.TestMain()
      /home/travis/gopath/src/github.com/georgysavva/scany/pgxscan/pgxscan_test.go:219 +0x38
  main.main()
      _testmain.go:112 +0x333
Goroutine 40 (running) created at:
  testing.(*T).Run()
      /home/travis/.gimme/versions/go1.13.12.linux.amd64/src/testing/testing.go:960 +0x651
  testing.runTests.func1()
      /home/travis/.gimme/versions/go1.13.12.linux.amd64/src/testing/testing.go:1202 +0xa6
  testing.tRunner()
      /home/travis/.gimme/versions/go1.13.12.linux.amd64/src/testing/testing.go:909 +0x199
  testing.runTests()
      /home/travis/.gimme/versions/go1.13.12.linux.amd64/src/testing/testing.go:1200 +0x521
  testing.(*M).Run()
      /home/travis/.gimme/versions/go1.13.12.linux.amd64/src/testing/testing.go:1117 +0x2ff
  github.com/georgysavva/scany/pgxscan_test.TestMain.func1()
      /home/travis/gopath/src/github.com/georgysavva/scany/pgxscan/pgxscan_test.go:218 +0x2b1
  github.com/georgysavva/scany/pgxscan_test.TestMain()
      /home/travis/gopath/src/github.com/georgysavva/scany/pgxscan/pgxscan_test.go:219 +0x38
  main.main()
      _testmain.go:112 +0x333
==================
```

**Comment by jackc** [comment] 2020-07-02 23:48
I suppose it wasn't explicitly forbidden in the docs, but the intention is definitely that calling any except certain allowed methods is forbidden after `Close()`. `Rows` is basically a cursor so once it is closed it is unusable.

I think in this case the race might actually be caused by `FieldDescriptions()`. That is definitely not safe to call after `Close()`. `Scan()` probably _is_ safe -- or could be made so -- but it would be much simpler and safer to forbid it.

The only safe methods to call on a closed `Rows` are `Close()`, `Err()`, and `CommandTag()`. Other methods may happen to work depending on the circumstances but that should not be relied on. I've added documentation for this (11428bbc02a720cf612d528ae07ab7aa8422ba18).

As far as anything beyond documentation... Not all of the unsafe methods return an error. The only valid action I can see is to panic. In general I don't like panics, but this is a case where it is a program bug, not an error condition that can be handled so it might be appropriate.

On the other hand calling these methods after `Close()` from a single Goroutine presumably does work now. So adding a panic could break seemingly working code. On the other hand, it _is_ a latent bug waiting to be triggered, so maybe it is worth it.

**Comment by georgysavva** [comment] 2020-07-03 08:46
Docs look good. I agree with panics, since it's a programming error. But, for example, `database/sql` returns that error in such  case:
```
var errRowsClosed = errors.New("sql: Rows are closed")
```

**Comment by georgysavva** [comment] 2020-07-17 09:21
Hi. What is the resolution on this? Should I submit a PR that adds panics in that case? Or we are good as it's now and should close this issue?

**Comment by jackc** [comment] 2020-07-18 13:21
For now I am satisfied with just the doc change.

Longer term I have some ideas that may make it safe to read `FieldDescriptions()` after the rows is closed. There is an unfortunate behavior now where you can't read them before reading a row and you can't read them after the rows is closed. This means you cannot ever read them if the result is 0 rows (because the first call to `.Next()` closes the rows). I'd like to change this, but it needs some care to avoid a performance hit.

**Comment by georgysavva** [comment] 2020-07-20 18:38
Okay got it. Thanks for explaining this. Let's keep the issue open then.

**Comment by bfontaine** [comment] 2022-11-07 10:10
Two years later, is keeping this issue open still relevant?

**Closed** 2023-06-02 14:08 UTC
Labels: needs response
