### ISSUE TITLE
pgbouncer transaction pooling mode

### ISSUE THREAD

**Issue by fmstephe** [jackc/pgx#344] opened 2017-10-19 16:15 UTC
Our application produces errors on every query when connected to pgbouncer which is set to use `transaction` pooling. Is it expected that pgx can communicate with pgbouncer in this pooling mode?

**Comment by fmstephe** [comment] 2017-10-20 08:35
A further update to this issue. We determined that the likely reason for failure was that when calling `(*ConnPool).Query(queryStr, args...)` pgx will use prepared statements by default.

I have tried to switch to using `(*ConnPool).QueryEx(context.Background(), queryStr, &pgx.QueryExOptions{SimpleProtocol: true}, args...)` but then we get these kinds of error. 

`failed: Scan received wrong number of arguments, got 0 but expected 2 trace:`

**Comment by fmstephe** [comment] 2017-10-31 22:05
@galdor currently we have given up on transaction/session pooling modes. But I would really like to use them. If I get the time to dive back in and try to find a solution I will post it here.

**Comment by galdor** [comment] 2017-11-02 09:30
We also went back to session mode. I'll keep the ticket updated if we find a better solution.

**Comment by kelseyfrancis** [comment] 2017-11-04 03:23
The issue might be that that [pgx itself makes a few queries after it connects (to look up types)](https://github.com/jackc/pgx/blob/master/conn.go#L385), and those would get prepared first, like any other query without its parameter oids supplied explicitly or not using the simple protocol.

**Comment by fmstephe** [comment] 2017-11-06 12:49
Thanks for the pointer @kelseyfrancis when I get to this I will look there first.

**Comment by james-lawrence** [comment] 2017-11-25 00:31
duplicate of #331

**Comment by jackc** [comment] 2019-08-31 14:44
Not sure if this is still relevant to the OP, but this can be handled with `PreferSimpleProtocol` in `v3`. In `v4` a describe mode statement cache can be used to still be able to use the extended protocol.

**Closed by jackc** 2019-08-31 14:44 UTC
