### ISSUE TITLE
"Received unknown message type: C" when continuously open 2 non-exist large object

### ISSUE THREAD

**Issue by leslie-qiwa** [jackc/pgx#439] opened 2018-07-30 22:39 UTC
Seems like this can be consistently reproduced after upgrading to Postgres 10 (ubuntu 18.04.1 LTS).

Reproduce steps:
- use `create database test` to create one empty database test.
- run below programs (note that 16843, 16839 are non-exist lo_object IDs):
```
func main() {
  config, err := pgx.ParseDSN("host=localhost:5432 dbname=test")
  if err != nil {
    fmt.Println(err)
    return
  }

  parts := strings.Split(config.Host, ":")
  config.Host = parts[0]

  pool, err := pgx.NewConnPool(pgx.ConnPoolConfig{
    ConnConfig:     config,
    MaxConnections: 5,
  })  
  if err != nil {
    fmt.Println(err)
    return
  }

  for _, id := range []pgx.Oid{16843, 16839} {
    tx, err := pool.Begin()
    if err != nil {
      fmt.Println(err)
      return
    }   

    objs, err := tx.LargeObjects()
    if err != nil {
      fmt.Println(err)
      return
    }   

    obj, err := objs.Open(id, pgx.LargeObjectModeRead)
    if err != nil {
      fmt.Println(err)
    } else {
      err = obj.Close()
      if err != nil {
        fmt.Println(err)
        return
      }   
    }   
    tx.Rollback()
  }
  pool.Close()
}
```

Then you will see output like 
```
ERROR: large object 16843 does not exist (SQLSTATE 42704)
Received unknown message type: C
```

version of ubuntu, postgres, go and pgx are
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
$ /usr/lib/postgresql/10/bin/postgres --version
postgres (PostgreSQL) 10.4 (Ubuntu 10.4-0ubuntu0.18.04)
$ go version
go version go1.10.3 linux/amd64

github.com/jackc/pgx v2.11.0
```

Not sure if it is postgres 10 issue, or pgx issue, but thought to start with pgx firstly. Thanks for looking into.

**Comment by leslie-qiwa** [comment] 2018-07-31 06:28
Thanks for quick reply. With latest version, seems like I got below panic
```
ERROR: large object 16843 does not exist (SQLSTATE 42704)
panic: runtime error: index out of range

goroutine 1 [running]:
encoding/binary.binary.bigEndian.Uint32(...)
        /usr/local/go/src/encoding/binary/binary.go:111
github.com/pensando/test-infra/vendor/github.com/jackc/pgx.fpInt32(...)
        /go/src/github.com/pensando/test-infra/vendor/github.com/jackc/pgx/fastpath.go:108
github.com/pensando/test-infra/vendor/github.com/jackc/pgx.(*LargeObjects).Open(0xc42018e000, 0x40000000041c7, 0x0, 0x0, 0x0)
        /go/src/github.com/pensando/test-infra/vendor/github.com/jackc/pgx/large_objects.go:72 +0x235
main.main()
        /go/src/github.com/pensando/test-infra/jobd/cmd/jobclean/loopen/main.go:48 +0x34f
```

If I change to close the object even if it has error. Seems like it is fine. Are you able to see it?
```
    obj, err := objs.Open(id, pgx.LargeObjectModeRead)
    if err != nil {
      fmt.Println(err)
      obj.Close()
    } else {
```

**Comment by ikitiki** [comment] 2018-07-31 06:35
sorry, I was testing against master branch, not v3.1.0, my bad.
in v3.1.0 I see the same error as you mentioned

**Comment by leslie-qiwa** [comment] 2018-07-31 06:37
No problem at all. Thanks for looking into the issue!

**Comment by jackc** [comment] 2019-08-31 15:13
It appears this is working and the issue is over a year old so I am going to close this now.

**Closed by jackc** 2019-08-31 15:13 UTC
