### ISSUE TITLE
read tcp XXX:YYYY->XXX:5432: i/o timeout

### ISSUE THREAD

**Issue by trashhalo** [jackc/pgx#831] opened 2020-09-11 17:59 UTC
I've been trying to track down this i/o timeout error. It seems to happen more frequently when the server is under load but one just came in when the db was @ 3% cpu.

This is a go app running in a docker container on an alpine image running in aws ecs fargate.

This comes back when executing queries. In the latest case. `GetContext` call. The entire time it waited was 56.21ms

I've been digging around pgx/pgconn code trying to understand it but running out ideas.

---

digging around the internet this `read tcp ... i/o timeout` issue seems to be a relatively common problem across many different systems. https://www.google.com/search?q=read+tcp+i/o+timeout+golang+site:stackoverflow.com

---
This appears to be the line in go that generates this error.
https://github.com/golang/go/blob/b115207baf6c2decc3820ada4574ef4e5ad940ec/src/net/net.go#L179

might be related too
https://github.com/golang/go/blob/e9ad52e46dee4b4f9c73ff44f44e1e234815800f/src/net/net.go#L573-L580

**Comment by bkeroackdsc** [comment] 2020-09-21 19:02
I'm seeing a lot of these errors. My unit tests run perfectly but at runtime lots of queries fail with these timeout errors, which I don't see with (for example) pq. I don't know if #701 is the answer, or if I'm doing something incorrectly but it's been frustrating so far.

**Comment by bkeroackdsc** [comment] 2020-09-21 19:05
For debug purposes I added a goroutine to the AfterConnect hook that pings every connection once a second. I see it pinging successfully, then a query timeout error, and (weirdly) the ping transiently fails with connection busy (presumably while the connection was busy with the query) and then it pings fine again.

Log output:
```
[...]
db: ping connection
db: ping connection
2020/09/18 00:12:16 error getting build: error getting build by id: failed to connect to `host=postgresql user=postgres database=furan`: failed to receive message (read tcp 172.17.0.7:53542->10.103.202.101:5432: i/o timeout)
2020/09/18 00:12:16 error listening for build events: error waiting for notification: 7d68435a-451b-438c-a0c9-bd7f173b5c03: read tcp 172.17.0.7:53538->10.103.202.101:5432: i/o timeout
error pinging connection: conn busy
db: ping connection
db: ping connection
db: ping connection
```

**Comment by trashhalo** [comment] 2020-09-21 20:46
What I ended up doing to try and reduce customer impact was wrapping our api with envoy which has built in error retry mechanisms. Obviously I'd rather the connection to the DB to be stable, but I'm out of ideas on how fix this.

**Comment by bkeroackdsc** [comment] 2020-10-05 22:39
My issue ended up being context cancellation that I wasn't expecting. The `i/o timeout` message meant "your context is cancelled" but it wasn't very clear to me.

**Comment by jackc** [comment] 2020-10-06 00:40
You may want to use the timeout helper function in the pgconn package. https://pkg.go.dev/github.com/jackc/pgconn#Timeout

**Comment by adw1n** [comment] 2021-03-21 22:29
I'm a bit confused by the context cancellation handling. Minimal example:
```
	if _, err := db.QueryContext(ctx, "select pg_sleep(3);"); err != nil {
		return err
	}
```

In this example when context gets cancelled `pq` would return `57014` SQLSTATE code:
> pq: canceling statement due to user request

pgx returns:
> read tcp 172.x.y.z:port1->172.a.b.c:port2: i/o timeout

When handling the error it makes a whole lot of difference if the error was a genuine network error or cancelled context.

@jackc  are you saying that this is the intended pgx behavior? This blocks me from migrating from `pq` to `pgx`.

**Comment by jackc** [comment] 2021-03-22 13:04
Yes, it is intended behavior. Context cancellation immediately cuts the network connection and asynchronously sends the cancellation request to the server. Otherwise a network failure could block a cancelled context indefinitely.

**Comment by adw1n** [comment] 2021-03-22 16:34
I think I should be able to convert old code that used pq and checked:
```
(errors.As(err, &postgresError) && (postgresError.Code == "57014"))
```
to:
```
(errors.As(err, &postgresError) && (postgresError.Code == "57014")) ||
(pgconn.Timeout(err) && errors.Is(ctx.Err(), context.Canceled))
```

**Comment by atombender** [comment] 2021-04-14 22:11
> You may want to use the timeout helper function in the pgconn package. https://pkg.go.dev/github.com/jackc/pgconn#Timeout

The problem is distinguishing the error from a cancellation that occurs for other reasons. `pgconn.Timeout()` tests for `context.Cancelled`, which isn't _universally_ a timeout signal.

The only way to use `pgconn.Timeout()` "safely" is to always use it immediately on errors returned by pgx (or pgconn, etc.). If you wrap or pass the error on to higher-level layers, those layers can no longer know if the error came from pgx.

This would really benefit from being wrapped in some special error type at the origin, in pgx. Otherwise we'll have to do this in every single pgx call:

```go
func FetchStuff() (Data, error) {
  // ...
  if err := rows.Err(); err != nil {
    return nil, convertError(err)
  }
  // ...
}

func convertError(err error) error {
  if pgconn.Timeout(err) {
    return ErrPostgresTimeout
  }
  return err
}

var ErrPostgresTimeout = errors.New("timeout")
```

**Comment by dsantos** [comment] 2021-05-29 15:35
I am on the same situation described by @adw1n and @atombender. I can't gracefully handle a good amount of requests with context cancelled because pgx returns an "i/o timeout" which is not really a network timeout. The helper function mentioned by @jackc doesn't help in this situation 😟

**Comment by dsantos** [comment] 2021-07-27 07:32
I don't know about the others, but the fix from https://github.com/jackc/pgconn/commit/6996e8d6c546d45bab6f1e8b24c010f40f095e6e worked perfectly for me. Thanks @jackc

**Comment by bfontaine** [comment] 2022-11-03 10:28
I believe we can close this issue then. Please reopen it if you think it’s a mistake.

**Closed by bfontaine** 2022-11-03 10:28 UTC

**Comment by iamatsundere** [comment] 2024-05-30 10:02
I am having this issue `read tcp [::1]:55146->[::1]:5432: i/o timeout` when using pgx and go/bun within transaction, it occurs randomly. Does anyone face this again?  Here is the version of them:
- go/bun: github.com/uptrace/bun v1.2.1
- pgx: github.com/jackc/pgx/v5 v5.6.0
