### ISSUE TITLE
support of udt types

### ISSUE THREAD

**Issue by volkmarbuehringer** [jackc/pgx#266] opened 2017-04-15 11:32 UTC
I get an errormessage during scan:
{
  "Error": "can't scan into dest[1]: Scan cannot decode into *generrester.Weburl"
}

I try to scan into following struct:

type Guges struct {
    Id int32  `json:"id"`
    A *Weburl  `json:"a"`
}

I generate the structs from the PG dictionary and the nested structs compile wll in go.

I tried following struct which doesn't work either:
type Guges1 struct {
    Id int32  `json:"id"`
    Agger *[]Weburl  `json:"agger"`
}

the idea is to use array_agg in postgres  views for aggregated joins and than process this data in a loop in go,
so that 1:n joins are replaced with aggregated types and can be naturally processed in a struct in go

this would open up the road for mass-processing of data from postgres in a single loop in go
together with copy support it should be faster and more flexible than PLpg/SQL
smaller datasets can  easily be cached in maps and the joins be replaced by map lookups

**Comment by jackc** [comment] 2017-04-15 16:02
What is a `Weburl`? Are you trying to load nested structs/records?

**Comment by volkmarbuehringer** [comment] 2017-04-15 21:17
yes nested structs

and scanner interface doesn't help either because it takes only 1 interface and not
an array 

func (t *Weburl) ScanPgx(r *pgx.ValueReader) error {
	fmt.Println("hier da", r.Len(), r.Type())
	arr, stru := ScannerWeburl()
	err := pgx.Decode(r, arr[0])
	fmt.Println("hier ga", err, stru)
	return err
}

**Comment by jackc** [comment] 2017-04-15 22:00
What you can do is make a type for the array of `Weburl` then define `ScanPgx` on that.

```go
type WebURLs []WebURL

func (t *WebURLs) ScanPgx(r *pgx.ValueReader) error {
// ...
}
```

The harder part will be parsing the data from PostgreSQL. There are different challenges depending on if you parse the text or binary protocols.

If you try to decode the binary protocol you might find looking at the `record` decoder of the unreleased, upcoming version of pgx helpful: https://github.com/jackc/pgx/blob/v3/pgtype/record.go#L71

**Comment by volkmarbuehringer** [comment] 2017-04-16 09:29
thank you for your help.

I did as you said but the scanner interface works only for the struct not for []struct

{
  "Error": "can't scan into dest[1]: Scan cannot decode into *[]generrester.Weburl"
}

**Comment by volkmarbuehringer** [comment] 2017-04-16 11:51
I switched to the v3 branch of pgx
I registered the correct type, but I don't know how to register for binary decode

**Comment by volkmarbuehringer** [comment] 2017-04-16 12:32
normally I would think it should be possible to have just an array of interface{} like in scan() and use the existing functionality 
if the array stuff works generically only a handler function per struct would be needed which delivers the array of interfaces

it would be much better suited for go to have record types and array_agg in the sql than converting everything to json in postgres and unmarshalling it in go

I would  need  just a simple function for every struct which produces the data structures for scanning
I think generating structs fits nicely with a strictly typed rdbms
this approach is more typesafe than PLpg/sql itself, if the structs are generated from the database before compile you would get compile errors if there are mismatches with the database

the generation of the structs includes checking for nullable and using pointers if needed

combined with generation based on views and parameterized functions, which use record types
and array_agg pgx would be a very powerful extension of postgres if the support of 
merged structs can be easily achived

this stuff can easily be generated:

type Weburl struct {
	Id         int32      `json:"id"`
	Url        *string    `json:"url"`
	Zusatz     *int64     `json:"zusatz"`
	Created    *time.Time `json:"created"`
	W_cr_date  *time.Time `json:"w_cr_date"`
	W_upd_date *time.Time `json:"w_upd_date"`
	W_upd_uid  *string    `json:"w_upd_uid"`
	W_cr_uid   *string    `json:"w_cr_uid"`
	Addtime    *time.Time `json:"addtime"`
	Addtime1   *time.Time `json:"addtime1"`
	Flag       bool       `json:"flag"`
	Test       *float64   `json:"test"`
}
func ScannerWeburl() ([]interface{}, interface{}) {
	struT := new(Weburl)

	return []interface{}{
		&struT.Id,
		&struT.Url,
		&struT.Zusatz,
		&struT.Created,
		&struT.W_cr_date,
		&struT.W_upd_date,
		&struT.W_upd_uid,
		&struT.W_cr_uid,
		&struT.Addtime,
		&struT.Addtime1,
		&struT.Flag,
		&struT.Test,
	}, struT

}

**Comment by volkmarbuehringer** [comment] 2017-04-16 19:30
it works now with nested structs, arrays are another question mark

**Comment by jackc** [comment] 2017-04-17 13:33
For this error: `"can't scan into dest[1]: Scan cannot decode into *[]generrester.Weburl"` I think the problem is the value passed into `Scan` cannot be an array of the underlying type. It actually must be a named type. As in, it should be a `WebURLs` not `[]WebURL` where `WebURLs` is `type WebURLs []WebURL`. Otherwise the `ScanPgx` method is not available.

**Comment by volkmarbuehringer** [comment] 2017-04-17 17:30
everything works now
the only problem is the array cannot be a pointer type
with a pointer a get the error message 
"can't scan into dest[1]: cannot assign &[{7432 0xc420011900 0xc420011918 2017-01-01 00:00:00 +0000 UTC 2017-04-11 21:39:59.150539 +0000 UTC <nil> <nil> 0xc420011940 2017-04-04 00:00:00 +0000 UTC 2017-04-04 21:06:40.50725 +0200 CEST true <nil>} {7262 0xc420011960 0xc420011978 2017-02-27 22:40:31.013001 +0000 UTC 
04 21:06:40.50725 +0200 CEST true <nil>} {6922 0xc4201987c0 0xc4201987d8 2017-01-01 00:00:00 +0000 UTC 2017-04-11 21:39:59.150539 +0000 UTC 2017-04-14 12:58:52.388063 +0000 UTC 0xc420198800 <nil> 2017-04-04 00:00:00 +0000 UTC 2017-04-04 21:06:40.50725 +0200 CEST true <nil>}] to **generrester.ArWeburl"

**Comment by volkmarbuehringer** [comment] 2017-04-17 17:34
another question is can i register the types globally ?
in the moment I must register for every connection in the hook
(I use the version 3 branch )

**Comment by jackc** [comment] 2017-04-17 22:52
> with a pointer a get the error message
"can't scan into dest[1]: cannot assign &[{7432 0xc420011900 0xc420011918 2017-01-01 00:00:00 +0000 UTC 2017-04-11 21:39:59.150539 +0000 UTC 0xc420011940 2017-04-04 00:00:00 +0000 UTC 2017-04-04 21:06:40.50725 +0200 CEST true } {7262 0xc420011960 0xc420011978 2017-02-27 22:40:31.013001 +0000 UTC
04 21:06:40.50725 +0200 CEST true } {6922 0xc4201987c0 0xc4201987d8 2017-01-01 00:00:00 +0000 UTC 2017-04-11 21:39:59.150539 +0000 UTC 2017-04-14 12:58:52.388063 +0000 UTC 0xc420198800 2017-04-04 00:00:00 +0000 UTC 2017-04-04 21:06:40.50725 +0200 CEST true }] to **generrester.ArWeburl"

That looks like pointer to pointer. Try assigning to `*generrester.ArWeburl` instead of `**generrester.ArWeburl`.

> another question is can i register the types globally ?
in the moment I must register for every connection in the hook

At the moment the hook is the correct place. (I presume you are using `*ConnInfo.RegisterDataType()`). A global registry might happen in the future, but the ConnPool AfterConnect hook provides the needed functionality now, so it's not a priority.

**Comment by volkmarbuehringer** [comment] 2017-04-20 19:51
the stuff works really well
I think it is preferable reading nested structs and arrays into typed structs in go
over producing json in Postgres and having map[string]interface{} in go and using reflection

I would like to reduce the amount of code which is needed to support this and to have better support
in pgx for this stuff
some boilerplating will always be necessary because pgx can't know about any arbitrary structs
but it should be enough to give an array of interface{} with pointers to the struct elements

this is the code I copied from pgx and now I use it from my generated boilerplate:

https://github.com/volkmarbuehringer/restfest/blob/master/db/protocolldb.go

it should be possible to do some reintegration of this into pgx, then one needs only some simple
boilerplate stuff to use arbitrary complex structures and arrays in go

something like this:

func (dst *Weburl) DecodeBinary(ci *pgtype.ConnInfo, src []byte) error {
	if src == nil {
			return nil
	}
	struT := new(Weburl)  //here struct

       d:=  ScannerWeburlI(struT)  //here the array of interfaces with pointers,no reflection

	err := d.DecodeBinary(ci,src)  //decode it
	if err != nil {
		return err
	}
	*dst = *struT  //here the filled struct
	return nil
}

**Closed** 2019-08-31 13:35 UTC
