### ISSUE TITLE
Moving from pq to pgx

### ISSUE THREAD

**Issue by uwauwa** [jackc/pgx#905] opened 2021-01-12 08:04 UTC
we have migrated 250 instances web applications from lib/pq to pgx based on the performance promises

1. pgxpool.Connect is not working and was throwing connections timeout, this caused instances to freeze and break nginx with gateway time out, no matter how much increase nginx timeout, postgres rds memory
2. reverting back to pgx.Connect throw hundreds of busy connection messages and all concurrent queries, ajax services and API broken 
3. scan float64 is not possible, and forcing the float64 to scan pgx.Numeric on interfaces values broken the reporting for any numeric postgresql table
4. using sql driver to scan float64 on database/sql NullFloat64 added extra complexity and extra loop check made the performance gain over pq useless

we had to revert back to lib/pq.
we believe this is not production ready and the performance statement should be amended on your page.

ubunut 20/aws ec2, postgresql12.5 /aws rds, go1.5,
gobwas/ws latest
lib/pq  latest
pgx latest

**Comment by zeroallox** [comment] 2021-01-12 14:28
I found a workaround for scanning to float64.

- Import "github.com/jackc/pgtype"
- Define an instance of pgtype.Float8 outside your scan.Next() loop
- Scan into that

Example:

```
	var f64 pgtype.Float8

	for rows.Next() == true {
		err = rows.Scan(&f64)
		if err != nil {
			return nil, err
		}
	}
```

**Comment by lesovsky** [comment] 2021-02-01 11:04
@uwauwa 
For every issue it's better to provide steps to reproduce and detailed explanations like code examples, error texts, etc.

**Comment by uwauwa** [comment] 2021-02-04 08:06
Read here https://github.com/jackc/pgx/issues/494#issuecomment-447605602
Read here https://github.com/jackc/pgx/issues/150#issuecomment-223243863

**Comment by gcsjo** [comment] 2021-08-02 08:20
@uwauwa Can you please provide more information if the reported issues have been fixed so far..

We believe we have the same issues and I found your comments just now, the connection issue similar to what we have and we can't fix it by the pool connection setting, it might be a race condition.

**Comment by drakkan** [comment] 2021-08-02 08:44
Hi,

I'm not related to the pgx project in any way and I don't want to be rude, but complaining doesn't fix anything. 

Guys if you have an issue can you please post a small standalone reproducer so others can take a look? Have you ever thought that the issue could be in your code? Thanks

**Comment by bfontaine** [comment] 2022-10-25 09:49
I’m closing this issue because I’m not sure what’s really actionable here. Feel free to reopen if you think it’s a mistake.

**Closed by bfontaine** 2022-10-25 09:49 UTC
