### ISSUE TITLE
p.p.CreateResource undefined

### ISSUE THREAD

**Issue by karbhawono** [jackc/pgx#741] opened 2020-05-10 17:17 UTC
Hi,

I;m just trying to play with the shortened_urls example but having this error:

src/github.com/jackc/pgx/pgxpool/pool.go:334:7: p.p.CreateResource undefined (type *puddle.Pool has no field or method CreateResource)

Any hint ?

----
Playing around, I'm changing this line to make it work.

p.p.Acquire(ctx)
// p.p.CreateResource(ctx)`

**Comment by jackc** [comment] 2020-05-13 13:47
I just tested the url_shortener example on master and it seems to work.

Not sure exactly what you're trying to do, but puddle is an internal implementation detail of pgxpool. In normal usage you should never run into it.

**Comment by bfontaine** [comment] 2022-10-25 09:59
I’m closing this since the issue can’t be reproduced. Feel free to reopen with more details.

**Closed by bfontaine** 2022-10-25 09:59 UTC
