### ISSUE TITLE
RowToStructByPos doesn't work with embedded structs

### ISSUE THREAD

**Issue by ric980** [jackc/pgx#1583] opened 2023-04-26 15:33 UTC
**Describe the bug**

The RowToStructByPos method returns the following error when used with embedded structs: "got 5 values, but dst struct has only 1 fields".

**To Reproduce**

The example is not runnable, but should be rather obvious.

```go
type activeUser struct {
	Id      int
	Email   string
}

type expiredUser struct {
	activeUser
	Expired string
}

sql := "SELECT id, email, to_char(expired, 'YYYY-MM-DD HH24:MI:SS') FROM users"
rows, _ := pgxpool.Query(context.Background(), sql)
users, err :=  pgx.CollectRows(rows, pgx.RowToStructByPos[expiredUser])
```

**Expected behavior**

I should get a slice of expired users.

**Actual behavior**

I get this error: got 5 values, but dst struct has only 1 fields.

**Version**
 - Go:  go version go1.20.3 darwin/arm64
 - PostgreSQL:  15
 - pgx: 5.3.1

**Comment by jackc** [comment] 2023-04-28 02:06
I assume the "5 values" is an oversight when creating the example? I get a "3 values".

It works if `activeUser` is changed to `ActiveUser`. So it seems the problem is the non-exported type. 

...

Hmm... didn't realize that exported fields of an unexported struct embedded in exported struct are visible. 🤯 Wow.

Well, fixed in f59e8bf5551f403e6b7ec0912097bce85ea21351.

**Closed by jackc** 2023-04-28 02:06 UTC
Labels: bug
