### ISSUE TITLE
v3.6.0 lost some table logic replication wals

### ISSUE THREAD

**Issue by Kfanup** [jackc/pgx#630] opened 2019-10-19 01:38 UTC
we have one table call "order", maybe there is a problem with processing keywords, we lost the table changes.

**Comment by bfontaine** [comment] 2022-11-04 09:59
I’m closing the issue since it’s more than 3-years-old and doesn’t have a snippet to reproduce it.

**Closed by bfontaine** 2022-11-04 09:59 UTC
