### ISSUE TITLE
Add LoadTypes method for bulk type registration

### ISSUE THREAD

**Issue by ewhauser** [jackc/pgx#2036] opened 2024-05-30 15:41 UTC
**Is your feature request related to a problem? Please describe.**

We are loading a large number of enums/custom domain objects (50+) using `AfterConnect` and `LoadType` as described in #1549. The `LoadType` method issues a SQL query for every type which is inefficient for a large number of enums as it makes a two SQL queries against the pg catalog. 

**Describe the solution you'd like**

A `LoadTypes` method that takes an slice of strings and returns a slice of `pgtype.Type` pointers would allow for a single roundtrip to the database.

**Comment by ewhauser** [comment] 2024-05-30 15:47
Actually, depending on the type, there are 3-4 queries run per item

**Comment by jackc** [comment] 2024-05-31 01:18
Duplicate of https://github.com/jackc/pgx/issues/2030.

**Closed by jackc** 2024-05-31 01:18 UTC
