### ISSUE TITLE
Possible rxMsg bug

### ISSUE THREAD

**Issue by josephglanville** [jackc/pgx#93] opened 2015-09-14 03:47 UTC
Hi,

I have been trying to track down a mysterious hang and I think it may be a pgx bug.
Here is a stack trace of the goroutine that is hung:

```
goroutine 97 [IO wait, 18 minutes]:
net.(*pollDesc).Wait(0xc20813a990, 0x72, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/flynn/flynn/util/_toolchain/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20813a990, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/flynn/flynn/util/_toolchain/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20813a930, 0xc20819a000, 0x2000, 0x2000, 0x0, 0x7f028754edb0, 0xc20800b8b0)
        /home/ubuntu/go/src/github.com/flynn/flynn/util/_toolchain/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208036e08, 0xc20819a000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/flynn/flynn/util/_toolchain/go/src/net/net.go:121 +0xdc
bufio.(*Reader).Read(0xc20813e900, 0xc20819a000, 0x2000, 0x2000, 0x5e, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/flynn/flynn/util/_toolchain/go/src/bufio/bufio.go:164 +0x13a
io.(*LimitedReader).Read(0xc2081b8060, 0xc20819a000, 0x2000, 0x2000, 0x5e, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/flynn/flynn/util/_toolchain/go/src/io/io.go:408 +0xce
io/ioutil.devNull.ReadFrom(0x0, 0x7f0287550bd8, 0xc2081b8060, 0x1ea, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/flynn/flynn/util/_toolchain/go/src/io/ioutil/ioutil.go:151 +0xb1
io/ioutil.(*devNull).ReadFrom(0xc20800a2f0, 0x7f0287550bd8, 0xc2081b8060, 0x7f0287550c28, 0x0, 0x0)
        <autogenerated>:9 +0xbb
io.Copy(0x7f028754ecb0, 0xc20800a2f0, 0x7f0287550bd8, 0xc2081b8060, 0x0, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/flynn/flynn/util/_toolchain/go/src/io/io.go:358 +0x13d
io.CopyN(0x7f028754ecb0, 0xc20800a2f0, 0x7f0287550430, 0xc20813e900, 0x5062, 0x16, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/flynn/flynn/util/_toolchain/go/src/io/io.go:327 +0x113
github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx.(*msgReader).rxMsg(0xc2080b3710, 0x0, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx/msg_reader.go:36 +0xa7
github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx.(*Conn).rxMsg(0xc2080b3200, 0x0, 0xc2080b3710, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx/conn.go:923 +0x84
github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx.(*Conn).Prepare(0xc2080b3200, 0x0, 0x0, 0xc2081abd60, 0x91, 0xc208135680, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx/conn.go:496 +0xcf6
github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx.(*Conn).Query(0xc2080b3200, 0xc2081abd60, 0x91, 0xc208111b20, 0x2, 0x2, 0x2, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx/query.go:428 +0x2c2
github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx.(*ConnPool).Query(0xc2080b00e0, 0xc2081abd60, 0x91, 0xc208111b20, 0x2, 0x2, 0x91, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx/conn_pool.go:196 +0x149
github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx.(*ConnPool).QueryRow(0xc2080b00e0, 0xc2081abd60, 0x91, 0xc208111b20, 0x2, 0x2, 0x3)
        /home/ubuntu/go/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx/conn_pool.go:210 +0x5a
github.com/flynn/flynn/pkg/postgres.(*DB).QueryRow(0xc20808f4e0, 0xc2081abd60, 0x91, 0xc208111b20, 0x2, 0x2, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/flynn/flynn/pkg/postgres/postgres.go:137 +0x7e
main.selectApp(0x7f0287553a10, 0xc20808f4e0, 0xc20813b1fa, 0x24, 0x0, 0x0, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/flynn/flynn/controller/app.go:128 +0x275
main.(*AppRepo).Get(0xc20812a2a0, 0xc20813b1fa, 0x24, 0x0, 0x0, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/flynn/flynn/controller/app.go:136 +0x8c
main.func·009(0x7f02875538a8, 0xc20812bd40, 0x7f02875538e8, 0xc20812bb60, 0xc2081a12b0)
        /home/ubuntu/go/src/github.com/flynn/flynn/controller/controller.go:352 +0xdd
github.com/flynn/flynn/pkg/httphelper.HandlerFunc.ServeHTTP(0xc20801ec80, 0x7f02875538a8, 0xc20812bd40, 0x7f02875538e8, 0xc20812bb60, 0xc2081a12b0)
        /home/ubuntu/go/src/github.com/flynn/flynn/pkg/httphelper/httphelper.go:101 +0x55
github.com/flynn/flynn/pkg/httphelper.func·002(0x7f02875538e8, 0xc20812bb60, 0xc2081a12b0, 0xc208135640, 0x2, 0x2)
        /home/ubuntu/go/src/github.com/flynn/flynn/pkg/httphelper/httphelper.go:108 +0xcb
github.com/flynn/flynn/Godeps/_workspace/src/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc20801e640, 0x7f02875538e8, 0xc20812bb60, 0xc2081a12b0)
        /home/ubuntu/go/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/julienschmidt/httprouter/router.go:276 +0x188
main.func·008(0x7f02875538e8, 0xc20812bb60, 0xc2081a12b0)
        /home/ubuntu/go/src/github.com/flynn/flynn/controller/controller.go:303 +0x44b
net/http.HandlerFunc.ServeHTTP(0xc20801ef40, 0x7f02875538e8, 0xc20812bb60, 0xc2081a12b0)
        /home/ubuntu/go/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/server.go:1265 +0x41
github.com/flynn/flynn/pkg/httphelper.func·004(0x7f02875538e8, 0xc20812bb60, 0xc2081a12b0)
        /home/ubuntu/go/src/github.com/flynn/flynn/pkg/httphelper/request_logger.go:34 +0x8a0
net/http.HandlerFunc.ServeHTTP(0xc20812ec30, 0x7f02875538e8, 0xc20812bb60, 0xc2081a12b0)
        /home/ubuntu/go/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/server.go:1265 +0x41
github.com/flynn/flynn/pkg/httphelper.func·003(0x7f0287553830, 0xc2081abb80, 0xc2081a12b0)
        /home/ubuntu/go/src/github.com/flynn/flynn/pkg/httphelper/httphelper.go:121 +0x25c
net/http.HandlerFunc.ServeHTTP(0xc20801ef60, 0x7f0287553830, 0xc2081abb80, 0xc2081a12b0)
        /home/ubuntu/go/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc208034ae0, 0x7f0287553830, 0xc2081abb80, 0xc2081a12b0)
        /home/ubuntu/go/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2081abae0)
        /home/ubuntu/go/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /home/ubuntu/go/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/server.go:1751 +0x35e
```

By the looks of it we tried to read when there were no bytes to read causing it to block on IO or something similar.
Have you encountered this before and is there any debugging code I could insert to work out if this is pgx issue or application code issue? I can reliably reproduce.

That said, it could still be a race condition because it has managed to get through my test without errors before but I can reproduce 9/10 times.

**Comment by jackc** [comment] 2015-09-14 14:39
At the moment there is no low level debug logging in pgx. At one point I added some, but there was a definite performance overhead because the logger interface requires calling the log method even if the log method will be filtered out later.

So at this point when I have to debug a wire interface level problem, I just add print statements temporarily. I know it's not ideal...

A hang at that location does indicate a blocked read. That happened once before due to not reading a complete message. That caused reading the next message to read bytes from the previous message as the new message length. If that length was very big it would cause a hang.

Given that it does succeed occasionally it does feel like a race condition. Perhaps a connection is being used after it has been returned to the connection pool. Two simultaneous uses of a connection could potentially cause this type of corruption.

**Comment by jackc** [comment] 2015-09-14 15:27
I created a new branch "log-bench" which does some logging for every received message. This may help in debugging.

**Comment by alaska** [comment] 2015-09-14 20:04
Why not just use build tags like dfc does [here](http://dave.cheney.net/2014/09/28/using-build-to-switch-between-debug-and-release)? You could do something similar for at least the trace level and then I believe it would be optimized out when not using the flag.

**Comment by josephglanville** [comment] 2015-09-14 22:19
I ran my failure case with the debug log enabled: https://gist.github.com/anonymous/d37e2b1a945c6cc36aaa

Unfortunately I couldn't spot the problem. The application also uses log15 but the debug logs are tagged with lib=postgres for the logger that is passed into the connection config.

**Comment by jackc** [comment] 2015-09-15 03:03
@alaska That's a good idea. I hadn't thought of build tags. I also raised an issue on the log15 project about performance for high-volume logging and got a suggestion that might be applicable. Hope to do something on that front sometime this week.

@josephglanville Nothing looks out of the ordinary with that debug log. It looks like the log was from running the application. Are there any test cases that produce the problem I could see? Hopefully I when I get more detailed tracing put into pgx that should shed more light on this.

**Comment by josephglanville** [comment] 2015-09-15 03:06
@jackc unfortunately the only reliable reproduction is an integration test that requires a bit of setup.
I haven't had any luck trying to reduce it down to a smaller test case that reproduces the issue.

**Comment by josephglanville** [comment] 2015-09-15 03:13
If it helps any the query that causes the issue is constructed here: https://github.com/josephglanville/flynn/blob/pkg_postgres_pgx/controller/app.go#L120

This function is called about 145 times during the test in question usually only 1 hangs.
I haven't been able to work out if it's always "same" one though as there is some async/non-deterministic components in play.

**Comment by josephglanville** [comment] 2015-09-15 03:13
Also possibly useful information but it always seems to hang while preparing the query, not whilst executing it.

**Comment by josephglanville** [comment] 2015-09-15 08:37
Thinking it might have been related to Prepare I took the liberty of preparing the statements ahead of time. However all this proved is Prepare is not to blame:

```
goroutine 124 [IO wait]:
net.(*pollDesc).Wait(0xc20820b4f0, 0x72, 0x0, 0x0)
        /vagrant/util/_toolchain/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20820b4f0, 0x0, 0x0)
        /vagrant/util/_toolchain/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20820b490, 0xc2080f4000, 0x8000, 0x8000, 0x0, 0x7fe735237db0, 0xc20814f838)
        /vagrant/util/_toolchain/go/src/net/fd_unix.go:242 +0x40f
:
io.ReadFull(0x7fe735239430, 0xc2080e3080, 0xc2080b2518, 0x5, 0x80, 0x4fb94f, 0x0, 0x0)
        /vagrant/util/_toolchain/go/src/io/io.go:316 +0x6d
github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx.(*msgReader).rxMsg(0xc2080b2510, 0x1900000019, 0x0, 0x0)
        /home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx/msg_reader.go:40 +0x12f
github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx.(*Conn).rxMsg(0xc2080b2000, 0xc2081145a0, 0xc2081145a0, 0x0, 0x0)
        /home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx/conn.go:925 +0x84
github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx.(*Rows).Next(0xc20803da00, 0xc2080ff11a)
        /home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx/query.go:161 +0x71
github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx.(*Row).Scan(0xc20803da00, 0xc2080ff650, 0x7, 0x7, 0x0, 0x0)
        /home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx/query.go:25 +0x9b
github.com/flynn/flynn/pkg/postgres.rowErrFixer.Scan(0x7fe735239c28, 0xc20803da00, 0xc2080ff650, 0x7, 0x7, 0x0, 0x0)
        /home/vagrant/go/src/github.com/flynn/flynn/pkg/postgres/postgres.go:169 +0x8e
github.com/flynn/flynn/pkg/postgres.(*rowErrFixer).Scan(0xc20814c760, 0xc2080ff650, 0x7, 0x7, 0x0, 0x0)
        <autogenerated>:27 +0xcf
main.scanApp(0x7fe735239c50, 0xc20814c760, 0x11, 0x0, 0x0)
        /vagrant/controller/app.go:102 +0x2eb
github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx.(*msgReader).rxMsg(0xc2080b2510, 0x1900000019, 0x0, 0x0)
        /vagrant/util/_toolchain/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7fe735239430, 0xc2080e3080, 0xc2080b2518, 0x5, 0x80, 0x4fb94f, 0x0, 0x0)
        /vagrant/util/_toolchain/go/src/io/io.go:316 +0x6d
github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx.(*msgReader).rxMsg(0xc2080b2510, 0x1900000019, 0x0, 0x0)
        /home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx/msg_reader.go:40 +0x12f
github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx.(*Conn).rxMsg(0xc2080b2000, 0xc2081145a0, 0xc2081145a0, 0x0, 0x0)
        /home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx/conn.go:925 +0x84
github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx.(*Rows).Next(0xc20803da00, 0xc2080ff11a)
        /home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx/query.go:161 +0x71
github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx.(*Row).Scan(0xc20803da00, 0xc2080ff650, 0x7, 0x7, 0x0, 0x0)
        /home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx/query.go:25 +0x9b
github.com/flynn/flynn/pkg/postgres.rowErrFixer.Scan(0x7fe735239c28, 0xc20803da00, 0xc2080ff650, 0x7, 0x7, 0x0, 0x0)
        /home/vagrant/go/src/github.com/flynn/flynn/pkg/postgres/postgres.go:169 +0x8e
github.com/flynn/flynn/pkg/postgres.(*rowErrFixer).Scan(0xc20814c760, 0xc2080ff650, 0x7, 0x7, 0x0, 0x0)
        <autogenerated>:27 +0xcf
main.scanApp(0x7fe735239c50, 0xc20814c760, 0x11, 0x0, 0x0)
        /vagrant/controller/app.go:102 +0x2eb
main.selectApp(0x7fe73523ca40, 0xc2080c36b0, 0xc2080ff11a, 0x24, 0x0, 0x0, 0x0, 0x0)
        /vagrant/controller/app.go:131 +0x265
main.(*AppRepo).Get(0xc20812fa70, 0xc2080ff11a, 0x24, 0x0, 0x0, 0x0, 0x0)
        /vagrant/controller/app.go:135 +0x8c
main.func<C2><B7>009(0x7fe73523c678, 0xc208114570, 0x7fe73523c6b8, 0xc2081142d0, 0xc208131e10)
        /vagrant/controller/controller.go:353 +0xdd
github.com/flynn/flynn/pkg/httphelper.HandlerFunc.ServeHTTP(0xc208148780, 0x7fe73523c678, 0xc208114570, 0x7fe73523c6b8, 0xc2081142d0, 0xc208131e10)
        /home/vagrant/go/src/github.com/flynn/flynn/pkg/httphelper/httphelper.go:101 +0x55
github.com/flynn/flynn/pkg/httphelper.func<C2><B7>002(0x7fe73523c6b8, 0xc2081142d0, 0xc208131e10, 0xc2080e5580, 0x2, 0x2)
        /home/vagrant/go/src/github.com/flynn/flynn/pkg/httphelper/httphelper.go:108 +0xcb
github.com/flynn/flynn/Godeps/_workspace/src/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc2081484a0, 0x7fe73523c6b8, 0xc2081142d0, 0xc208131e10)
        /home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/julienschmidt/httprouter/router.go:276 +0x188
main.func<C2><B7>008(0x7fe73523c6b8, 0xc2081142d0, 0xc208131e10)
        /vagrant/controller/controller.go:304 +0x44b
net/http.HandlerFunc.ServeHTTP(0xc2081489c0, 0x7fe73523c6b8, 0xc2081142d0, 0xc208131e10)
        /vagrant/util/_toolchain/go/src/net/http/server.go:1265 +0x41
github.com/flynn/flynn/pkg/httphelper.func<C2><B7>004(0x7fe73523c6b8, 0xc2081142d0, 0xc208131e10)
        /home/vagrant/go/src/github.com/flynn/flynn/pkg/httphelper/request_logger.go:34 +0x8a0
net/http.HandlerFunc.ServeHTTP(0xc208109710, 0x7fe73523c6b8, 0xc2081142d0, 0xc208131e10)
        /vagrant/util/_toolchain/go/src/net/http/server.go:1265 +0x41
github.com/flynn/flynn/pkg/httphelper.func<C2><B7>003(0x7fe73523c600, 0xc208151f40, 0xc208131e10)
        /home/vagrant/go/src/github.com/flynn/flynn/pkg/httphelper/httphelper.go:121 +0x25c
net/http.HandlerFunc.ServeHTTP(0xc2081489e0, 0x7fe73523c600, 0xc208151f40, 0xc208131e10)
        /vagrant/util/_toolchain/go/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc2080e2d80, 0x7fe73523c600, 0xc208151f40, 0xc208131e10)
        /vagrant/util/_toolchain/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208151a40)
        /vagrant/util/_toolchain/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /vagrant/util/_toolchain/go/src/net/http/server.go:1751 +0x35e
```

**Comment by jackc** [comment] 2015-09-16 15:34
Try the latest version of branch "log-bench". I've added a few things that may help tease out the bug.

There is now a new "trace" log level. You can activate it by setting the pgx.ConnConfig.LogLevel to pgx.LogLevelTrace. This allows efficiently filtering out the most verbose messages without requiring any breaking changes. Trace messages will be logged at the debug level by log15 (it doesn't have a trace level). With this in place I was able to add much more detailed logging with only a negligible performance when tracing is not enabled.

Also, I added guard clauses to Query and Exec to detect and fail fast if they are called on a connection that is already running a Query or Exec.

I'll leave these changes on a branch for a little while, but now that the performance impact these tools is acceptable I will probably merge them to master soon.

**Comment by josephglanville** [comment] 2015-09-16 20:57
I ran the most minimal case I could but it's still somewhat verbose.
https://gist.github.com/josephglanville/84d0150fa9d154888561
I also included a stack trace of the hung goroutine.

**Comment by josephglanville** [comment] 2015-09-16 20:59
The query that hung was a prepared query called `release_select` which may help when combing the log.

**Comment by jackc** [comment] 2015-09-17 14:20
Have you run this with the race detector enabled? The only likely candidates I can think of is some sort of race where a connection gets used multiple times simultaneously or a message is only partially consumed or over-consumed. But these cases have guards to either entirely prevent the error, or at least detect it and return an error.

Another few data points might be to run with a connection pool size of 1. That should effectively serialize the test. Might help indicate if it is a race.

**Comment by josephglanville** [comment] 2015-09-17 20:27
Ok, so I think I have tracked this down to releasing connections that still have listener subscriptions.
pgx doesn't currently track subscriptions so on Release a connection will reside in the pool with the subscription still active and can be checked out by another user.

Very subtle and painful. I am going to knock together a PR that introduces subscription tracking on per connection basis so no one else has to endure this pain again lol.

**Comment by josephglanville** [comment] 2015-09-17 20:57
I created #95 to illustrate what I think should happen, what do you think @jackc?

**Comment by jackc** [comment] 2015-09-17 22:50
It'd be great if not unlistening before releasing into the pool is the problem, but if so that is only a surface cause. pgx's listen support is designed to handle notification messages at any time -- expected or not. It is handled in conn.processContextFreeMsg which is called in every message listener loop.

Not unlistening before releasing to the connection pool would cause a memory leak, as all the notifications would buffer in Conn.notifications indefinitely, but it should never cause the type of problem you have been experiencing.

I added some stress testing around concurrent listen/notify in 90b2e0acb73239b10b272629ddbd5570401102f2 but I was unable to detect any errors.

I know you said it is hard to set up a test environment, but by chance could it be wrapped in a docker image I could grab, or set up on a VM I could shell into?

**Comment by josephglanville** [comment] 2015-09-17 23:49
If you are familiar with vagrant I could help you setup an environment that would replicate the problem.

Fixing the listener leak has worked around the issue for me but as you say, it indicates a deeper problem and I would like to see that fixed if at all possible.

**Comment by jackc** [comment] 2015-09-18 02:31
I'm slightly familiar with vagrant. I have it installed and know how to pull down a project and run `vagrant up` and `vagrant ssh`. But I've never done anything other than as a consumer. If that's enough, great.

**Comment by jackc** [comment] 2015-10-26 17:13
Not sure if this is still an issue, but if you are using TLS, the problem may have been related to #103 which is now fixed.

**Comment by titanous** [comment] 2015-10-26 17:15
We have `ssl_renegotiation_limit` set to 0 on all of our servers. We did spot this bug a week ago happening consistently on what appeared to be a relatively slow server (not owned by us), but were not able to replicate on a slow EC2 instance.

**Comment by josephglanville** [comment] 2015-12-19 20:08
I was able to run into this again. I need to build a minimal test case but I think this happens when a `LISTEN` is active, `ConnPool.Close()` is called and then at some later time while still waiting for the connection pool to close there is an attempted read on the listening connection, in the case I saw it was trying to `conn.Exec("UNLISTEN channel")`. Hopefully I can come up with exact minimal reproduction.

**Comment by jackc** [comment] 2016-01-29 23:47
While tracking down another issue on #103, I uncovered a bug in `msgReader.rxMsg`. When a msgReader encounters an error it internally records the failure. Then on any future calls a guard clause checks to see if the msgReader is already in an error state and if so, immediately returns the previous error. The bug was the guard clause was returning, but instead of returning the previous error it was returning nil. This might have been the cause of this problem. It's fixed on master.

**Comment by jackc** [comment] 2016-07-08 18:44
Has this error reoccurred since the potential fix above was committed? I'd like to resolve this issue.

**Comment by josephglanville** [comment] 2016-07-08 22:40
@jackc not that I am aware of, happy to close this out.

**Closed** 2016-07-09 18:21 UTC
